name: element
version: '1.7.2'
summary: Glossy Matrix collaboration client
description: |
  All-in-one secure chat app for teams, friends and organisations. 
  Keeps conversations in your control, safe from data-mining and ads. 
  Talk to everyone through the open global Matrix network, 
  protected by proper end-to-end encryption.

grade: stable
confinement: strict
base: core18
architectures:
- build-on: amd64

parts:
  desktop-gtk3:
    build-packages:
    - build-essential
    - libgtk-3-dev
    make-parameters:
    - FLAVOR=gtk3
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libgtk-3-0
    - libgdk-pixbuf2.0-0
    - libglib2.0-bin
    - libgtk-3-bin
    - unity-gtk3-module
    - libappindicator3-1
    - locales-all

  musicblocks:
    plugin: dump
    source: https://github.com/srevinsaju/element-deb/releases/download/continuous/element-desktop_1.7.2_amd64.deb 
    source-type: deb
    after:
      - desktop-gtk3
    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
      - libdrm2
      - libgbm1
      - libwayland-server0
      - libx11-xcb1
      - libxcb-dri3-0
      - libgtk2.0-0

apps:
  element-desktop:
    command: env TMPDIR=$XDG_RUNTIME_DIR PATH=/usr/local/bin:${PATH} ${SNAP}/bin/desktop-launch $SNAP/opt/element-desktop/element-desktop --no-sandbox

plugs:
  desktop:
  desktop-legacy:
  x11:
  unity7:
  wayland:
  opengl:
  home:
  gsettings:
  browser-support:
  pulseaudio:
  network:

