name: element-desktop
version: '1.7.2'
summary: Glossy Matrix collaboration client
description: |
  All-in-one secure chat app for teams, friends and organisations. 
  Keeps conversations in your control, safe from data-mining and ads. 
  Talk to everyone through the open global Matrix network, 
  protected by proper end-to-end encryption.

grade: devel
confinement: devmode
base: core18
architectures:
- build-on: amd64

parts:

  element-desktop:
    plugin: nodejs
    nodejs-version: "14.5.0"
    source: https://github.com/vector-im/riot-desktop
    source-type: git
    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libx11-xcb1
      - libxtst6
      - libxcb-dri3-0
      - libappindicator1
      - libsecret-1-0
      - libgtk-3-0
      - libdrm2
      - libgbm1
      - libdb5.3
      - libsqlcipher0
      - libglu1-mesa
 
    build-packages:
      - wget
      - libsqlcipher-dev
    override-build: | 
      yarn install
      yarn run hak
      mkdir config && cd config
      wget https://raw.githubusercontent.com/vector-im/riot-web/develop/config.sample.json
      mv config.sample.json config.json && cd ..
      yarn run fetch --importkey
      yarn run fetch --cfgdir config
      wget https://raw.githubusercontent.com/srevinsaju/element-deb/master/appimage.js
      mv appimage.js src/.
      wget https://raw.githubusercontent.com/srevinsaju/element-deb/master/patch.sh
      chmod +x patch.sh
      ./patch.sh
      yarn run build:native
      yarn run build
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/element/
      rm -rf dist/linux-unpacked/chrome-sandbox
      mv dist/linux-unpacked/* $SNAPCRAFT_PART_INSTALL/usr/lib/element/.
  
  cleanup:
    after: [element-desktop]
    plugin: nil
    build-snaps: [ gnome-3-28-1804 ]
    override-prime: |
        set -eux
        cd /snap/gnome-3-28-1804/current
        find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;


apps:
  element-desktop:
    command: usr/lib/element/element-desktop --no-sandbox
    extensions: [gnome-3-28]
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/bin:$SNAP/usr/lib:$SNAP/usr/local/lib:$SNAP/usr/lib/element:$LD_LIBRARY_PATH 
      TMPDIR: $XDG_RUNTIME_DIR
      XDG_CURRENT_DESKTOP: Unity
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
    plugs: [home, network, network-observe, x11, wayland, opengl, desktop, desktop-legacy, unity7, gsettings, browser-support]
 
