name: element-desktop
version: '1.7.2'
summary: Glossy Matrix collaboration client
description: |
  All-in-one secure chat app for teams, friends and organisations. 
  Keeps conversations in your control, safe from data-mining and ads. 
  Talk to everyone through the open global Matrix network, 
  protected by proper end-to-end encryption.

grade: stable
confinement: strict
base: core18
architectures:
- build-on: amd64

parts:

  desktop-gtk3:
    build-packages:
    - build-essential
    - libgtk-3-dev
    make-parameters:
    - FLAVOR=gtk3
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libgtk-3-0
    - libgdk-pixbuf2.0-0
    - libglib2.0-bin
    - libgtk-3-bin
    - unity-gtk3-module
    - libappindicator3-1
    - locales-all

  element-desktop:
    after:
      - desktop-gtk3
    plugin: nodejs
    nodejs-version: "14.5.0"
    source: https://github.com/vector-im/riot-desktop
    source-type: git
    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
      - libappindicator1
      - libsecret-1-0
      - libgtk-3-0
      - libdb5.3
      - libsqlcipher0
    build-packages:
      - wget
      - libsqlcipher-dev
    override-build: | 
      yarn install
      yarn run hak
      mkdir config && cd config
      wget https://raw.githubusercontent.com/vector-im/riot-web/develop/config.sample.json
      mv config.sample.json config.json && cd ..
      yarn run fetch --importkey
      yarn run fetch --cfgdir config
      wget https://raw.githubusercontent.com/srevinsaju/element-deb/master/appimage.js
      mv appimage.js src/.
      wget https://raw.githubusercontent.com/srevinsaju/element-deb/master/patch.sh
      chmod +x patch.sh
      ./patch.sh
      yarn run build:native
      yarn run build
      npm install electron -g  
    install:
      mkdir -p usr/lib/element/
      mv dist/linux-unpacked/resources/* usr/lib/element/


apps:
  element-desktop:
    command: bin/desktop-launch $SNAP/usr/bin/electron $SNAP/usr/lib/element/app.asar "$@"

    plugs: [home, network, network-observe, x11, wayland, opengl, desktop, desktop-legacy, unity7, gsettings, browser-support]
 
